### PR TITLE
#ISSUE-2043 Add logic lost in code refactor for silent fail on rewards

### PR DESCRIPTION
**Pull request by jimmiehansson**
This is a PR proposal to add the logic again for silent fail as per issue https://github.com/lbryio/lbry-desktop/issues/2043

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Thanks for the PR @jimmiehansson! Can we send you [LBC as appreciation](https://lbry.io/faq/appreciation)?

**Comment by seanyesmunt** [comment]
@skhameneh I just ran `yarn build` on this branch and it seems to have taken all of the walletEncrypt stuff out. Any ideas why?

**Comment by seanyesmunt** [comment]
I guess it doesn't matter since `lbryinc` doesn't use that. I'm gonna merge this.

**Comment by jimmiehansson** [comment]
@seanyesmunt Sure thing, i'll be glad to give a hand when needed, this was very simple though.
I'd be glad to have this count for the Hacktober event if possible, any issue of priority on a bigger scale?

**Comment by tzarebczan** [comment]
@jimmiehansson please reach out to us at hello@lbry.io so we an we [send you some LBC as appreciation](https://lbry.io/faq/appreciation) and get you a t-shirt for Hacktoberfest :)

**Pull request merged**
